# Generated by Django 4.1.2 on 2022-10-31 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('profileName', models.CharField(default='', max_length=50)),
                ('bio', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
