# Generated by Django 4.1.2 on 2022-11-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_profile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.TextField(max_length=200)),
                ('volunteer_type', models.CharField(choices=[('build', 'Build'), ('food', 'Food'), ('clean', 'Clean')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='profiles.profile')),
            ],
        ),
    ]
