# Generated by Django 4.1.3 on 2022-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted')], max_length=8),
        ),
    ]
